apiVersion: apps/v1
kind: Deployment
metadata:
  name: atmosphere
  namespace: ecosync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: atmosphere
  template:
    metadata:
      labels:
        app: atmosphere
    spec:
      containers:
      - name: atmosphere
        image: sahilll22/ecosync:atmosphere-BUILD_NUMBER
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecosync-config
              key: ATMOSPHERE_PORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecosystem
  namespace: ecosync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecosystem
  template:
    metadata:
      labels:
        app: ecosystem
    spec:
      containers:
      - name: ecosystem
        image: sahilll22/ecosync:ecosystem-BUILD_NUMBER
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: ecosync-config
              key: ECOSYSTEM_PORT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thermal
  namespace: ecosync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thermal
  template:
    metadata:
      labels:
        app: thermal
    spec:
      containers:
      - name: thermal
        image: sahilll22/ecosync:thermal-BUILD_NUMBER
        ports:
        - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: ecosync
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: sahilll22/ecosync:gateway-BUILD_NUMBER
        ports:
        - containerPort: 3000
        env:
        - name: ATMOSPHERE_URL
          valueFrom:
            configMapKeyRef:
              name: ecosync-config
              key: ATMOSPHERE_URL
        - name: THERMAL_URL
          valueFrom:
            configMapKeyRef:
              name: ecosync-config
              key: THERMAL_URL
        - name: ECOSYSTEM_URL
          valueFrom:
            configMapKeyRef:
              name: ecosync-config
              key: ECOSYSTEM_URL
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: ecosync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: sahilll22/ecosync:web-BUILD_NUMBER
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: ecosync-config
              key: VITE_API_URL
